name: Scala
on:
  pull_request: {}
  push:
    branches:
      - series/2.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v18

      - name: "Run with ${{ matrix.java }} 🚀"
        run: nix develop -c sbt 'clean;mdoc;++test'
