name: Scala
on:
  pull_request: {}
  push:
    branches:
      - series/2.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v6.4

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v31.2.0

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v16
        with:
          name: profunktor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Run Scala tests 🚀"
        run: nix run .#sbt -- 'clean;mdoc;+test;+mimaReportBinaryIssues'
