name: Release
on:
  push:
    branches:
      - series/1.x
    tags:
      - "*"

jobs:
  build:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0 # fetch all branches & tags

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v18

      - name: "Publish ${{ github.ref }} 🚀"
        env:
          PGP_PASSPHRASE: "${{ secrets.PGP_PASSPHRASE }}"
          PGP_SECRET: "${{ secrets.PGP_SECRET }}"
          SONATYPE_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
          SONATYPE_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
        run: nix develop -c sbt ci-release
